"""add remaining dark photo id column to the Shift table

Revision ID: 8a67bb7ce09f
Revises: 6f03c4d03223
Create Date: 2025-01-04 12:43:46.007325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a67bb7ce09f'
down_revision: Union[str, None] = '6f03c4d03223'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shifts', sa.Column('end_shift_light_tobacco_photo_id', sa.Text(), nullable=True))
    op.add_column('shifts', sa.Column('end_shift_dark_tobacco_photo_id', sa.Text(), nullable=True))
    op.drop_column('shifts', 'end_shift_tobacco_photo_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shifts', sa.Column('end_shift_tobacco_photo_id', sa.TEXT(), nullable=True))
    op.drop_column('shifts', 'end_shift_dark_tobacco_photo_id')
    op.drop_column('shifts', 'end_shift_light_tobacco_photo_id')
    # ### end Alembic commands ###
