name: Test Telegram Bot Build

on:
  push:
    branches:
      - '*' # Запускать на всех ветках

jobs:
  test-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t test-telegram-bot .

      - name: Run Telegram Bot in container
        env:
          BOT_TOKEN: ${{ secrets.TEST_BOT_TOKEN }}
          DATA_BASE_URL: ${{ secrets.DATA_BASE_URL }}
        run: |
          docker run -d --name telegram-bot-container \
            -e BOT_TOKEN=${BOT_TOKEN} \
            -e DATA_BASE_URL=${DATA_BASE_URL} \
            test-telegram-bot

      - name: Wait for bot to start
        run: |
          echo "Waiting for 10 seconds to allow the bot to start..."
          sleep 10

      - name: Check container status
        run: |
          STATUS=$(docker inspect -f '{{.State.Status}}' telegram-bot-container)
          if [ "$STATUS" = "running" ]; then
            echo "Container is running successfully."
          else
            echo "Container failed to start. Status: $STATUS"
            exit 1
          fi

      - name: Stop and clean up container
        if: always()
        run: |
          docker stop telegram-bot-container
          docker rm telegram-bot-container