name: Test Telegram Bot Build

on:
  push:
    branches:
      - '*' # Запускать на всех ветках

jobs:
  test-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t test-telegram-bot .

      - name: Run tests in temporary Docker container
        env:
          BOT_TOKEN: ${{ secrets.TEST_BOT_TOKEN }}
          DATA_BASE_URL: ${{ secrets.DATA_BASE_URL }}
        run: |
          docker run --rm \
            -e BOT_TOKEN=${BOT_TOKEN} \
            -e DATA_BASE_URL=${DATA_BASE_URL} \
            test-telegram-bot \
            /bin/bash -c "
              python -m pip install --upgrade pip && \
              pip install -r requirements.txt && \
              python hookah_space_bot.py & \
              sleep 10 && \
              if pgrep -f 'hookah_space_bot.py'; then
                echo 'Bot is running successfully.';
              else
                echo 'Bot failed to start.';
                exit 1;
              fi
            "