name: Deploy Telegram Bot to OVH

on:
  push:
    branches:
      - "*"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Аутентификация в Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Сборка и публикация Docker-образа
      - name: Build and push Docker image
        run: |
          docker build --cache-from ${{ secrets.DOCKER_USERNAME }}/hookah_space_bot:latest -t ${{ secrets.DOCKER_USERNAME }}/hookah_space_bot:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/hookah_space_bot:latest

      # 4. Перезапуск контейнера с выполнением миграции в одном шаге
      - name: Deploy to OVH Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.OVH_SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/hookah_space_bot:latest
            # Стоп и удаление старого контейнера
            docker stop hookah_space_bot || true
            docker rm hookah_space_bot || true
            
            # Запуск контейнера с миграциями (alembic upgrade head)
            docker run --rm \
              -v ~/hookah_space_bot_data:/app/data \
              -e DATA_BASE_URL=${{ secrets.DATA_BASE_URL }} \
              -e BOT_TOKEN=${{ secrets.PROD_BOT_TOKEN }} \
              ${{ secrets.DOCKER_USERNAME }}/hookah_space_bot:latest /usr/local/bin/alembic upgrade head

            # Перезапуск контейнера с ботом
            docker run -d --name hookah_space_bot \
              --restart always \
              -v ~/hookah_space_bot_data:/app/data \
              -e DATA_BASE_URL=${{ secrets.DATA_BASE_URL }} \
              -e BOT_TOKEN=${{ secrets.PROD_BOT_TOKEN }} \
              ${{ secrets.DOCKER_USERNAME }}/hookah_space_bot:latest
